export const homeTypes = {
  SET_NAME: 'SET_NAME',
  GET_CURRENT_LOCATION: 'GET_CURRENT_LOCATION',
  GET_INPUT_DATA: 'GET_INPUT_DATA',
  TOGGLE_SEARCH_RESULT: 'TOGGLE_SEARCH_RESULT',
  GET_ADDRESSES_PREDICTIONS: 'GET_ADDRESSES_PREDICTIONS',
};

export default homeTypes;
